'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={system:null,processes:[],applications:[],lifecycle:[],machines:[],selectedId:'local',sort:'cpu_percent',dir:-1,lifeFilter:'All',graph:[],pollBusy:false,appsBusy:false,page:'overview'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clamp=n=>Math.max(0,Math.min(100,Number(n)||0));
const pct=n=>Number.isFinite(+n)?`${(+n).toFixed(1)}%`:'N/A';
const gbFromKb=n=>Number.isFinite(+n)?`${(+n/1048576).toFixed(1)} GiB`:'N/A';
function bytes(n){n=+n;if(!Number.isFinite(n))return'N/A';const u=['B','KiB','MiB','GiB','TiB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i?1:0)} ${u[i]}`}
function rate(n){n=+n;if(!Number.isFinite(n))return'N/A';return`${bytes(n)}/s`}
function duration(s){s=+s;if(!Number.isFinite(s))return'N/A';let d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return`${d}d ${h}h ${m}m`}
function time(ms){if(!ms)return'—';return new Date(ms).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function age(ms){ms=+ms;if(!Number.isFinite(ms))return'—';return ms<1000?`${ms} ms`:`${(ms/1000).toFixed(1)} s`}
async function api(path,opt={}){const o={...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}};const r=await fetch(path,o);let d;try{d=await r.json()}catch{d={error:`HTTP ${r.status}`}}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
let toastTimer;function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2400)}

function setPage(name){if(!document.querySelector(`#page-${name}`))name='overview';state.page=name;$$('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${name}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===name));const active=$(`#page-${name}`);$('#crumbPage').textContent=active?.dataset.title||'Overview';history.replaceState(null,'',`#${name}`);if(name==='overview')requestAnimationFrame(drawChart)}
$$('.nav-item').forEach(b=>b.onclick=()=>setPage(b.dataset.page));
window.addEventListener('hashchange',()=>setPage(location.hash.slice(1)||'overview'));

function renderSystem(s){state.system=s;const remote=s.source==='remote';$('#sourceBadge').textContent=remote?'REMOTE':'LOCAL';$('#liveText').innerHTML=`<i></i> ${String(s.status||'LIVE').includes('LIVE')?'LIVE':'STATUS'}`;$('#machineHostname').textContent=s.hostname||s.machine_name||'—';const machineMeta=[s.distribution,s.kernel,s.uptime_seconds!=null?`Uptime ${duration(s.uptime_seconds)}`:''];$('#machineOs').textContent=machineMeta.filter(Boolean).join(' · ')||'—';$('#lastRefresh').textContent=time(s.timestamp_ms);$('#dataAge').textContent=age(s.measurement_freshness_ms);
 $('#cpuMetric').innerHTML=`${(+s.cpu_percent||0).toFixed(1)}<span class="unit">%</span>`;$('#cpuSub').textContent=`${s.cpu_cores??'—'} logical cores`;$('#cpuBar').style.width=`${clamp(s.cpu_percent)}%`;
 const mem=s.memory||{};$('#ramMetric').innerHTML=`${(+mem.percent||0).toFixed(1)}<span class="unit">%</span>`;$('#ramSub').textContent=`${gbFromKb(mem.used_kb)} / ${gbFromKb(mem.total_kb)}`;$('#ramBar').style.width=`${clamp(mem.percent)}%`;
 const disk=s.disk||{};$('#diskMetric').innerHTML=`${(+disk.percent||0).toFixed(1)}<span class="unit">%</span>`;$('#diskSub').textContent=`${bytes(disk.used_bytes)} / ${bytes(disk.total_bytes)} · root /`;$('#diskBar').style.width=`${clamp(disk.percent)}%`;
 const pr=s.processes||{};$('#procMetric').textContent=pr.total??'—';$('#procSub').textContent=`${pr.running??'—'} running · ${pr.sleeping??'—'} sleeping`;$('#processPageCount').textContent=pr.total??state.processes.length;
 const net=s.network||{};$('#rxMetric').innerHTML=`${rate(net.rx_rate_bps).replace(/ (\S+)$/,'<span class="unit"> $1</span>')}`;$('#txMetric').innerHTML=`${rate(net.tx_rate_bps).replace(/ (\S+)$/,'<span class="unit"> $1</span>')}`;
 const sw=s.swap||{};$('#swapMetric').innerHTML=`${gbFromKb(sw.used_kb).replace(/ (\S+)$/,'<span class="unit"> $1</span>')}`;$('#swapSub').textContent=`${gbFromKb(sw.total_kb)} allocated`;$('#swapBar').style.width=`${clamp(sw.percent)}%`;
 const load=s.load||[];$('#loadMetric').textContent=Number.isFinite(+load[0])?(+load[0]).toFixed(2):'—';$('#loadSub').textContent=`${(+load[0]||0).toFixed(2)} · ${(+load[1]||0).toFixed(2)} / 5m · 15m`;
 $('#cpuModel').textContent=s.cpu_model||'—';$('#distribution').textContent=s.distribution||'—';$('#kernel').textContent=s.kernel||'—';$('#uptime').textContent=duration(s.uptime_seconds);$('#threadCount').textContent=pr.threads??'—';$('#availableRam').textContent=gbFromKb(mem.available_kb);const ips=(net.interfaces||[]).map(n=>n.ipv4).filter(Boolean);$('#ipv4').textContent=ips.length?ips.join(', '):'N/A';
 renderNetwork(s);state.graph.push({cpu:+s.cpu_percent||0,ram:+mem.percent||0});if(state.graph.length>75)state.graph.shift();drawChart();renderMachines();}

function drawChart(){const c=$('#resourceChart');if(!c||!c.getContext||state.page!=='overview')return;const rect=c.getBoundingClientRect();const dpr=devicePixelRatio||1;c.width=Math.max(1,Math.round(rect.width*dpr));c.height=Math.max(1,Math.round(rect.height*dpr));const x=c.getContext('2d');x.scale(dpr,dpr);const w=rect.width,h=rect.height;x.clearRect(0,0,w,h);x.strokeStyle='#1a272e';x.lineWidth=1;for(let i=0;i<=4;i++){const y=14+(h-30)*i/4;x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke();x.fillStyle='#55656c';x.font='9px system-ui';x.fillText(`${100-i*25}%`,4,y-4)}const pts=state.graph;if(pts.length<2)return;function line(key,color){x.beginPath();pts.forEach((p,i)=>{const px=i*(w/(Math.max(74,pts.length-1)));const py=14+(h-30)*(1-clamp(p[key])/100);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle=color;x.lineWidth=1.6;x.stroke()}line('cpu','#73d69d');line('ram','#6bc8d9')}
window.addEventListener('resize',drawChart);

function renderNetwork(s){const n=s.network||{},ifs=n.interfaces||[];$('#netRxRate').textContent=rate(n.rx_rate_bps);$('#netTxRate').textContent=rate(n.tx_rate_bps);$('#netRxTotal').textContent=`${bytes(n.rx_bytes)} total`;$('#netTxTotal').textContent=`${bytes(n.tx_bytes)} total`;$('#netIfCount').textContent=ifs.length;$('#networkList').innerHTML=ifs.length?ifs.map(i=>`<article class="card interface-card"><div class="interface-top"><h2>${esc(i.name)}</h2><span class="if-state ${String(i.state).toLowerCase()==='up'?'up':''}">${esc(String(i.state||'unknown').toUpperCase())}</span></div><div class="interface-ip">${esc(i.ipv4||'No IPv4')}</div><div class="interface-stats"><div><span>RECEIVED</span><b>${bytes(i.rx_bytes)}</b></div><div><span>TRANSMITTED</span><b>${bytes(i.tx_bytes)}</b></div></div></article>`).join(''):'<div class="card empty-block">No interfaces reported for this source.</div>'}

function processRows(){const q=$('#processSearch').value.trim().toLowerCase();let rows=state.processes.filter(p=>{if($('#runningOnly').checked&&p.state!=='R')return false;if($('#highCpu').checked&&+p.cpu_percent<20)return false;if($('#highMem').checked&&+p.ram_percent<2)return false;if(!q)return true;return[p.pid,p.ppid,p.user,p.state,p.name,p.cmdline].some(v=>String(v??'').toLowerCase().includes(q))});const f=state.sort,d=state.dir;rows.sort((a,b)=>{const av=a[f],bv=b[f];if(typeof av==='number'||typeof bv==='number')return((+av||0)-(+bv||0))*d;return String(av??'').localeCompare(String(bv??''))*d});return rows}
function renderProcesses(){const rows=processRows();$('#visibleCount').textContent=rows.length;$('#processPageCount').textContent=state.system?.processes?.total??state.processes.length;$('#processBody').innerHTML=rows.length?rows.map(p=>`<tr><td><span class="pid-link" data-pid="${p.pid}">${p.pid}</span></td><td>${p.ppid}</td><td>${esc(p.user)}</td><td><span class="state-pill">${esc(p.state)}</span></td><td title="${esc(p.cmdline)}"><b>${esc(p.name)}</b></td><td class="${+p.cpu_percent>=20?'cpu-hot':''}">${(+p.cpu_percent).toFixed(2)}</td><td>${(+p.ram_mb).toFixed(2)}</td><td>${(+p.ram_percent).toFixed(2)}</td><td>${p.threads}</td><td>${esc(p.start_time)}</td></tr>`).join(''):'<tr><td colspan="10" class="empty">No processes match the filters.</td></tr>';$$('.pid-link').forEach(x=>x.onclick=()=>openInspector(x.dataset.pid))}
$$('#processTable th[data-sort]').forEach(th=>th.onclick=()=>{const f=th.dataset.sort;if(state.sort===f)state.dir*=-1;else{state.sort=f;state.dir=['name','user','state','start_time'].includes(f)?1:-1}renderProcesses()});['processSearch','runningOnly','highCpu','highMem'].forEach(id=>$('#'+id).addEventListener(id==='processSearch'?'input':'change',renderProcesses));

function cleanBrowserTitle(title,app){let t=String(title||'').trim();if(!t)return'';const pats=[new RegExp(`\\s*[-—]\\s*${String(app||'').replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\s*$`,'i'),/\s*[-—]\s*Google Chrome\s*$/i,/\s*[-—]\s*Microsoft Edge\s*$/i,/\s*[-—]\s*Mozilla Firefox\s*$/i];for(const p of pats)t=t.replace(p,'').trim();return t}
function renderApplications(d){const apps=d.applications||[];state.applications=apps;$('#openAppCount').textContent=apps.length;$('#appDetectionMode').textContent=d.available===false?(d.error||'Application detection unavailable'):(d.detection_mode||d.platform||'OS application detection');const br=apps.filter(a=>a.kind==='browser');$('#webAppSummary').innerHTML=br.length?`<span>BROWSER / WEB APP</span><div class="browser-chips">${br.map(a=>{const p=cleanBrowserTitle(a.title,a.application);return`<span class="browser-chip"><b>${esc(a.application)}</b><em>${esc(p||'Browser open · title unavailable')}</em></span>`}).join('')}</div>`:'<span>BROWSER / WEB APP</span><b>No visible browser window detected.</b>';$('#applicationsBody').innerHTML=apps.length?apps.map(a=>`<tr><td><b>${esc(a.application||a.name)}</b><small>${esc(a.name||'')}</small></td><td><span class="app-kind ${esc(a.kind||'application')}">${esc(String(a.kind||'application').toUpperCase())}</span></td><td>${a.pid??'N/A'}</td><td title="${esc(a.title||'')}">${esc(a.title||'—')}</td><td>${Number.isFinite(+a.cpu_percent)?(+a.cpu_percent).toFixed(2):'N/A'}</td><td>${Number.isFinite(+a.ram_mb)?(+a.ram_mb).toFixed(2):'N/A'}</td><td>${a.process_count??1}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">No open GUI applications detected for this source.</td></tr>';$('#appNote').textContent=d.note||'Application detection uses real OS data. No application values are simulated.'}

function renderLifecycle(){const all=state.lifecycle;$('#lifeBadge').textContent=all.length;let rows=all;if(state.lifeFilter!=='All')rows=rows.filter(e=>e.event===state.lifeFilter);$('#lifeSource').textContent=state.system?`${state.system.source==='remote'?'Remote':'Local'} · ${state.system.machine_name||state.system.hostname||''}`:'Live source';$('#lifecycleList').innerHTML=rows.length?rows.slice(0,180).map(e=>`<div class="life-row"><span>${time(e.timestamp_ms)}</span><span><b class="event-tag ${esc(e.event)}">${esc(e.event)}</b></span><span>${e.pid}</span><span>${e.ppid}</span><b>${esc(e.name)}</b><span>${(+e.cpu_percent).toFixed(1)}%</span><span>${(+e.ram_mb).toFixed(1)} MB</span><span>${e.lifetime_ms?`${(e.lifetime_ms/1000).toFixed(1)}s`:'—'}</span></div>`).join(''):'<div class="empty-block">No lifecycle events for this filter yet.</div>'}
$$('#lifecycleTabs button').forEach(b=>b.onclick=()=>{$$('#lifecycleTabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.lifeFilter=b.dataset.filter;renderLifecycle()});

async function openInspector(pid){$('#inspector').classList.add('open');$('#drawerBackdrop').classList.add('open');$('#inspector').setAttribute('aria-hidden','false');$('#inspectorTitle').textContent=`PID ${pid}`;$('#inspectorBody').innerHTML='<div class="empty-block">Reading live process data…</div>';try{const p=await api(`/api/process/${pid}`),m=p.memory||{},io=p.io||{};$('#inspectorBody').innerHTML=`<div class="detail-grid">${detail('Process',p.name)}${detail('State',p.state)}${detail('PID / PPID',`${p.pid} / ${p.ppid}`)}${detail('User',`${p.user??''} (${p.uid??'N/A'})`)}${detail('CPU',p.cpu_percent==null?'N/A':pct(p.cpu_percent))}${detail('RAM',p.ram_mb==null?'N/A':`${(+p.ram_mb).toFixed(2)} MB`)}${detail('Threads',p.threads)}${detail('Open FDs',p.open_fd_count??p.fd_status??'N/A')}${detail('Command',p.cmdline,'wide')}${detail('Executable',p.executable,'wide')}${detail('Working directory',p.cwd,'wide')}</div><h3 class="subhead">Memory address-space fields</h3><div class="detail-grid">${Object.entries(m).map(([k,v])=>detail(k,`${v} kB`)).join('')}</div><h3 class="subhead">Process I/O</h3><div class="detail-grid">${io.status?detail('Status',io.status,'wide'):Object.entries(io).map(([k,v])=>detail(k,bytes(v))).join('')}</div><h3 class="subhead">Memory maps</h3><button id="loadMaps" class="btn">Load /proc/${pid}/maps</button><div id="mapsBox"></div>`;$('#loadMaps').onclick=async()=>{const b=$('#mapsBox');b.innerHTML='<div class="empty-block">Loading maps…</div>';try{const d=await api(`/api/process/${pid}/maps`);b.innerHTML=`<pre class="maps">${esc(d.maps||d.status||'NO DATA')}</pre>`}catch(e){b.innerHTML=`<div class="empty-block">${esc(e.message)}</div>`}}}catch(e){$('#inspectorBody').innerHTML=`<div class="empty-block">${esc(e.message)}</div>`}}
function detail(k,v,cls=''){return`<div class="detail ${cls}"><span>${esc(k)}</span><b>${esc(v??'N/A')}</b></div>`}function closeInspector(){$('#inspector').classList.remove('open');$('#drawerBackdrop').classList.remove('open');$('#inspector').setAttribute('aria-hidden','true')}$('#closeInspector').onclick=closeInspector;$('#drawerBackdrop').onclick=closeInspector;

async function loadMachines(){try{const d=await api('/api/machines');state.machines=d.machines||[];state.selectedId=d.selected_id||'local';$('#machineSelect').innerHTML=state.machines.map(m=>`<option value="${esc(m.id)}" ${m.id===state.selectedId?'selected':''}>${esc(m.display_name)}</option>`).join('');renderMachines()}catch(e){toast(e.message)}}
function renderMachines(){const grid=$('#machinesGrid');if(!grid)return;grid.innerHTML=state.machines.map(m=>{const selected=m.id===state.selectedId;const live=state.system&&state.system.machine_id===m.id;return`<article class="card machine-tile ${selected?'selected':''}"><div class="machine-tile-head"><div><h3>${esc(m.display_name)}</h3><p>${m.is_local?'localhost':esc(m.host)}</p></div><span class="tile-status">${live?'● LIVE':selected?'SELECTED':'SAVED'}</span></div><dl><div><dt>Source</dt><dd>${m.is_local?'Local Linux':'Authorized SSH'}</dd></div><div><dt>Status</dt><dd>${live?'Live telemetry':'Standby'}</dd></div>${!m.is_local?`<div><dt>IPv4 / host</dt><dd>${esc(m.host)}</dd></div>`:''}</dl><div class="tile-actions"><button data-select="${esc(m.id)}">${selected?'Selected':'Monitor'}</button>${m.is_local?'':`<button class="remove" data-delete="${esc(m.id)}">Remove</button>`}</div></article>`}).join('');$$('[data-select]').forEach(b=>b.onclick=()=>selectMachine(b.dataset.select));$$('[data-delete]').forEach(b=>b.onclick=()=>deleteMachine(b.dataset.delete))}
async function selectMachine(id){try{await api('/api/select-machine',{method:'POST',body:JSON.stringify({id})});state.selectedId=id;state.graph=[];await loadMachines();toast('Monitoring source changed');setTimeout(pollOnce,100)}catch(e){toast(e.message)}}
async function deleteMachine(id){try{await api(`/api/machines/${encodeURIComponent(id)}`,{method:'DELETE'});await loadMachines();await pollOnce();toast('Machine removed')}catch(e){toast(e.message)}}
$('#machineSelect').onchange=e=>selectMachine(e.target.value);

async function quickConnect(ip,statusEl){ip=String(ip||'').trim();if(!ip){statusEl.textContent='Enter an IPv4 address.';statusEl.className='connect-status bad';return}statusEl.textContent=`Connecting to ${ip}…`;statusEl.className='connect-status';try{const d=await api('/api/quick-connect',{method:'POST',body:JSON.stringify({host:ip})});statusEl.textContent=`CONNECTED · ${d.display_name} · dashboard source switched`;statusEl.className='connect-status ok';state.selectedId=d.id;state.graph=[];await loadMachines();await pollOnce();toast(`Connected to ${d.display_name}`);setTimeout(()=>{closeQuickModal();setPage('overview')},550)}catch(e){statusEl.textContent=e.message;statusEl.className='connect-status bad'}}
$('#quickConnectBtn').onclick=()=>quickConnect($('#quickIp').value,$('#quickStatus'));$('#quickIp').addEventListener('keydown',e=>{if(e.key==='Enter')$('#quickConnectBtn').click()});
const modal=$('#quickModal');function openQuickModal(){modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('#modalStatus').textContent='No password is sent through the browser.';$('#modalStatus').className='connect-status';setTimeout(()=>$('#modalIp').focus(),50)}function closeQuickModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}$$('.open-quick-connect').forEach(b=>b.onclick=openQuickModal);$('#closeQuickModal').onclick=closeQuickModal;modal.addEventListener('click',e=>{if(e.target===modal)closeQuickModal()});$('#modalConnectBtn').onclick=()=>quickConnect($('#modalIp').value,$('#modalStatus'));$('#modalIp').addEventListener('keydown',e=>{if(e.key==='Enter')$('#modalConnectBtn').click()});

$('#runDemo').onclick=async()=>{const b=$('#runDemo');b.disabled=true;$('#demoOutput').textContent='Executing real fork / pipe / waitpid demo…';try{$('#demoOutput').textContent=JSON.stringify(await api('/api/process-demo',{method:'POST',body:'{}'}),null,2)}catch(e){$('#demoOutput').textContent=e.message}finally{b.disabled=false}};

async function pollOnce(){if(state.pollBusy)return;state.pollBusy=true;try{const [s,p,l]=await Promise.all([api('/api/system'),api('/api/processes'),api('/api/lifecycle')]);renderSystem(s);state.processes=p.processes||[];renderProcesses();state.lifecycle=l.events||[];renderLifecycle()}catch(e){$('#liveText').innerHTML='<i style="background:#f08b8b"></i> UNAVAILABLE';toast(e.message)}finally{state.pollBusy=false}}
async function pollApplications(){if(state.appsBusy)return;state.appsBusy=true;try{renderApplications(await api('/api/applications'))}catch(e){renderApplications({available:false,error:e.message,applications:[]})}finally{state.appsBusy=false}}
async function loop(){await pollOnce();setTimeout(loop,1000)}async function appLoop(){await pollApplications();setTimeout(appLoop,2500)}

setPage(location.hash.slice(1)||'overview');loadMachines().then(()=>{loop();appLoop()});
