#define _GNU_SOURCE
#include "monitor.h"
#include "process_demo.h"
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

static volatile sig_atomic_t stop_flag=0;static void on_sig(int s){(void)s;stop_flag=1;}
static void show(const MonitorSnapshot *s){printf("\033[2J\033[H");printf("Linux System Information and Resource Monitoring Tool\n");printf("Host: %s | %s | Kernel %s\n",s->system.hostname,s->system.distro,s->system.kernel);printf("CPU: %6.2f%% | Cores: %d | Load: %.2f %.2f %.2f\n",s->system.cpu_percent,s->system.cpu_cores,s->system.load1,s->system.load5,s->system.load15);printf("RAM: %6.2f%%  %.1f / %.1f MiB | Swap: %.2f%%\n",s->system.mem_percent,s->system.mem_used_kb/1024.0,s->system.mem_total_kb/1024.0,s->system.swap_percent);printf("Disk /: %6.2f%% | Uptime: %.0fs | Processes: %d (R:%d S:%d) | Threads: %ld\n",s->system.disk_percent,s->system.uptime_seconds,s->system.process_total,s->system.process_running,s->system.process_sleeping,s->system.thread_total);printf("Network: RX %.1f KiB/s | TX %.1f KiB/s\n",s->system.net_rx_rate_bps/1024.0,s->system.net_tx_rate_bps/1024.0);printf("\n%-7s %-7s %-12s %-4s %-24s %8s %10s %7s\n","PID","PPID","USER","ST","PROCESS","CPU%","RAM MiB","THR");size_t limit=s->process_count<18?s->process_count:18;for(size_t i=0;i<limit;i++){const ProcessInfo *p=&s->processes[i];printf("%-7d %-7d %-12.12s %-4c %-24.24s %8.2f %10.2f %7ld\n",p->pid,p->ppid,p->user,p->state,p->name,p->cpu_percent,p->ram_mb,p->threads);}fflush(stdout);}
int main(int argc,char **argv){int once=0,demo=0,interval=1;for(int i=1;i<argc;i++){if(strcmp(argv[i],"--once")==0)once=1;else if(strcmp(argv[i],"--process-demo")==0)demo=1;else if(strcmp(argv[i],"--interval")==0&&i+1<argc){interval=atoi(argv[++i]);if(interval<1||interval>60){fprintf(stderr,"Interval must be 1-60 seconds\n");return 2;}}else if(strcmp(argv[i],"--help")==0){printf("Usage: %s [--once] [--interval N] [--process-demo]\n",argv[0]);return 0;}else{fprintf(stderr,"Unknown option: %s\n",argv[i]);return 2;}}if(demo){char *j=NULL;if(run_process_ipc_demo_json(&j)!=0)return 1;puts(j);free(j);return 0;}struct sigaction sa;memset(&sa,0,sizeof(sa));sa.sa_handler=on_sig;sigemptyset(&sa.sa_mask);sigaction(SIGINT,&sa,NULL);sigaction(SIGTERM,&sa,NULL);MonitorSnapshot *prev=calloc(1,sizeof(*prev)),*s=calloc(1,sizeof(*s));if(!prev||!s){fprintf(stderr,"Out of memory\n");free(prev);free(s);return 1;}int rc=0;do{char err[256];if(collect_local_snapshot(s,prev->timestamp_ms?prev:NULL,err,sizeof(err))!=0){fprintf(stderr,"Collection failed: %s\n",err);rc=1;break;}show(s);*prev=*s;if(once)break;for(int k=0;k<interval*10&&!stop_flag;k++){struct timespec ts={0,100000000};nanosleep(&ts,NULL);}}while(!stop_flag);free(s);free(prev);if(!once)printf("\nStopped cleanly.\n");return rc;}
